[package]
name = "runtime"
version = "0.0.1"
authors = ["Trivaxy"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parser = { path = "../parser" }
num-complex = "0.3"
linked-hash-map = "0.5"