[package]
name = "parser"
version = "0.0.1"
authors = ["Trivaxy"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2"
pest_derive = "2"
glium = "0.28"
linked-hash-map = "0.5"